/*
 * This source file was generated by the Gradle 'init' task
 */
package firstrentverdict;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        // Local Development: If templates are found on disk, enable dev mode and set
        // path
        java.io.File jteDir = new java.io.File("app/src/main/jte");
        if (jteDir.exists()) {
            System.setProperty("gg.jte.templateLocation", "app/src/main/jte");
            System.setProperty("gg.jte.developmentMode", "true");
            System.setProperty("gg.jte.usePrecompiledTemplates", "false");
        } else if (new java.io.File("src/main/jte").exists()) {
            System.setProperty("gg.jte.templateLocation", "src/main/jte");
            System.setProperty("gg.jte.developmentMode", "true");
            System.setProperty("gg.jte.usePrecompiledTemplates", "false");
        }

        SpringApplication.run(App.class, args);
    }
}
